const int EVENTCOUNT_SOUNDS = 12;

// EVENTGROUPS
const int EVENTGROUP_NOTDEADYET_BOW = 0;
const int EVENTGROUP_NOTDEADYET_WALK = 1;
const int EVENTGROUP_NOTDEADYET_MAN = 2;
const int EVENTGROUP_NOTDEADYET_WOMAN = 3;
const int EVENTGROUP_NOTDEADYET_AMBIENCE = 4;
const int EVENTGROUP_NOTDEADYET_MENU = 5;

//EVENTS
const int EVENTID_NOTDEADYET_BOW_BOWSHOT = 0;
const int EVENTID_NOTDEADYET_BOW_BOWSTRETCH = 1;
const int EVENTID_NOTDEADYET_BOW_ARROWTREE = 2;
const int EVENTID_NOTDEADYET_WALK_GRASS = 3;
const int EVENTID_NOTDEADYET_MAN_RUN = 4;
const int EVENTID_NOTDEADYET_MAN_DRINKWATER = 5;
const int EVENTID_NOTDEADYET_MAN_DEATH = 6;
const int EVENTID_NOTDEADYET_WOMAN_RUN = 7;
const int EVENTID_NOTDEADYET_WOMAN_DRINKWATER = 8;
const int EVENTID_NOTDEADYET_WOMAN_DEATH = 9;
const int EVENTID_NOTDEADYET_AMBIENCE_FOREST = 10;
const int EVENTID_NOTDEADYET_MENU_TOGGLE_N_CLICK = 11;

const int EVENTCATEGORY_NOTDEADYET_MASTER = -1;
const int EVENTCATEGORY_NOTDEADYET_MASTER_MUSIC = 0;