#pragma once

//Should be increased if enums are added.
static const int KEY_CAP = 22;
enum KEY_BINDINGS
{
	KEY_FORWARD,
	KEY_BACKWARD,
	KEY_LEFT,
	KEY_RIGHT,
	KEY_SPRINT,
	KEY_JUMP,
	KEY_DUCK,
	KEY_INTERACT,
	KEY_MENU,
	KEY_INVENTORY,
	KEY_EQUIPMENT,
	MOUSE_LEFT_PRESS,
	MOUSE_RIGHT_PRESS,
	KEY_TEST,
	KEY_KILL,
	KEY_RESTART,
	KEY_ANIMAL_SWAP,
	KEY_EQUIP,
	KEY_DEBUG_INFO,
	KEY_READY,
	KEY_SWAP_EQ,
	KEY_PICKMENU
};